### ISSUE TITLE
cannot login

### ISSUE THREAD

**Issue by sakarimov** [maximmaxim345/sheepit-plugin#3]
i just tried this plugin, after installation i cannot login to sheepit

> Blender 3.0.0
>>	build date: 2021-12-03
	build time: 00:34:54
	build commit date: 2021-12-02
	build commit time: 18:35
	build hash: f1cca3055776
	build platform: Linux
	build type: release

**Comment by maximmaxim345** [comment]
Sheepit changed its website. The newest release should work now.
