### ISSUE TITLE
upload successfull but not appear in sheepit dashboard

### ISSUE THREAD

**Issue by sakarimov** [maximmaxim345/sheepit-plugin#5]
![image](https://user-images.githubusercontent.com/5676876/172093320-6b4f4837-ad3a-4acf-83bc-cc7bf42cc301.png)

my system is:
OS : Archlinux
Blender Version : 3.0.0
Plugin Version : 2.5

## Problem
i uploaded the file via the plugin, it said that the ```project uploaded```, but when i check my sheepit dashboard, i cannot see the project

**Comment by maximmaxim345** [comment]
The newest version should work again.
